// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetCoreBootcampT23MVC_EX3;

namespace NetCoreBootcampT23MVC_EX3.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("NetCoreBootcampT23MVC_EX3.Models.AsignadoA", b =>
                {
                    b.Property<string>("CientificoId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProyectoId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CientificoId", "ProyectoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("AsignacionesProyectos");
                });

            modelBuilder.Entity("NetCoreBootcampT23MVC_EX3.Models.Cientifico", b =>
                {
                    b.Property<string>("DNI")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("longtext");

                    b.HasKey("DNI");

                    b.ToTable("Cientificos");
                });

            modelBuilder.Entity("NetCoreBootcampT23MVC_EX3.Models.Proyecto", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("NetCoreBootcampT23MVC_EX3.Models.AsignadoA", b =>
                {
                    b.HasOne("NetCoreBootcampT23MVC_EX3.Models.Cientifico", "Cientifico")
                        .WithMany()
                        .HasForeignKey("CientificoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetCoreBootcampT23MVC_EX3.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cientifico");

                    b.Navigation("Proyecto");
                });
#pragma warning restore 612, 618
        }
    }
}
